import { client } from '$utils/sanity'
import groq from 'groq'

const BASE_URL = 'https://blog-not.vercel.app'

export async function GET() {
	const { posts, authors } = await client.fetch<{
		posts: Sanity.BlogPost[],
		authors: Sanity.BlogAuthor[],
	}>(groq`{
		'posts': *[_type == 'blog.post']|order(date desc){
			metadata,
			date
		}
	}`)

	return new Response(
		`<?xml version="1.0" encoding="UTF-8"?>
		<rss version="2.0">
			<channel>
				<title>The Artificial Blog</title>
				<link>${BASE_URL}</link>
				<description>Totally fake blog. Some are real, though. Generated by Chat GPT and Midjourney.</description>
				<language>en-us</language>

				${posts?.map(post => `<item>
					<title>${post.metadata.title}</title>
					<link>${BASE_URL}/blog/${post.metadata.slug.current}</link>
					<guid>${BASE_URL}/blog/${post.metadata.slug.current}</guid>
					<description>${post.metadata.description}</description>
				</item>`).join('')}
			</channel>
		</rss>`.trim(),
		{
			headers: {
				'content-type': 'application/xml'
			}
		}
	)
}
